### ISSUE TITLE
Anyong ah sahyoh

### ISSUE THREAD

**Issue by 8secz-johndpope** [metocherry/aws-lambda-image-video#1]
I wonder if you have the use case for
Webm -> mp4.

I'm looking to record webcam in browser then serve to aws lambda -> then s3 to convert.

**Comment by metocherry** [comment]
I haven't tried it yet. I'll give it a try.

**Comment by 8secz-johndpope** [comment]
I found this - https://github.com/gigo6000/gifmaker
It has a different approach using bash /ffmpeg and will spit out gif from mp4.
Do you think your approach with ffmpeg node will be less expensive over time with layers / memory footprint / time to execute?
UPDATe - I'll close this ticket - but still interested in feedback to question.
